version: '3.8'
services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5001:5173"
    volumes:
      - ./client/dist:/usr/share/nginx/html  # React build dosyalarını Nginx konteynerine bağla

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    working_dir: /app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Nginx'i 80 portundan dış dünyaya aç
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf  # Nginx yapılandırma dosyasını bağla
      - ./client/dist:/usr/share/nginx/html  # React build dosyalarını Nginx konteynerine bağla
    depends_on:
      - frontend  # Nginx, frontend servisi build edildikten sonra başlatılır
