apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmaster-rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmaster-rabbitmq
  template:
    metadata:
      labels:
        app: taskmaster-rabbitmq
    spec:
      containers:
      - name: taskmaster-rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
        - containerPort: 15672
        - containerPort: 5672
        env:
        - name: RABBITMQ_ERLANG_COOKIE
          value: "key123"
        - name: RABBITMQ_DEFAULT_USER
          value: "user"
        - name: RABBITMQ_DEFAULT_PASS
          value: "password"
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
      volumes: # 'volumes' bölümü 'containers' bölümünün dışında olmalı
      - name: rabbitmq-data
        emptyDir: {}


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: taskmaster-rabbitmq-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: taskmaster-rabbitmq
#   template:
#     metadata:
#       labels:
#         app: taskmaster-rabbitmq
#     spec:
#       containers:
#       - name: taskmaster-rabbitmq
#         image: zeynlf/taskmaster-rabbitmq:latest
#         ports: # Container'ın açık portlarını tanımlar.
#         - containerPort: 15672 # RabbitMQ yönetim arayüzü için port.
#         - containerPort: 5672 # RabbitMQ mesaj kuyruğu için port.
#         env: #  Container'a environment değişkenleri tanımlar.
#         - name: RABBITMQ_ERLANG_COOKIE
#           value: "key123"
#         - name: RABBITMQ_DEFAULT_USER
#           value: "user"
#         - name: RABBITMQ_DEFAULT_PASS
#           value: "password"
#         volumeMounts:
#         - name: rabbitmq-data
#           mountPath: /var/lib/rabbitmq
#         volumes:
#         - name: rabbitmq-data
#           emptyDir: {} # ptyDir türünde bir volume tanımlar. Bu tür volume, pod oluşturulduğunda boş bir dizin olarak oluşturulur ve pod silindiğinde silinir. Bu örnekte, RabbitMQ verilerini depolamak için kullanılır.
